services:
  postgres:
    container_name: pathrise-db
    ports:
      - '5432:5432'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=zack
      - POSTGRES_PASSWORD=pass
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - ./Backend/pathrise-DB/postgres-data:/var/lib/postgresql/data
      - ./Backend/pathrise-DB/data:/var/lib/dbdata
      - ./Backend/pathrise-DB/sql/PathriseSchema.sql:/docker-entrypoint-initdb.d/PathriseSchema.sql     
  node:
    container_name: pathrise-api
    ports:
      - '3001:3001'
    build: 
      context: ./Backend/pathrise-API/
      dockerfile: Dockerfile
    restart: always
  react:
    container_name: pathrise-frontend
    ports:
      - '3000:3000'
    build: 
      context: ./Frontend/
      dockerfile: Dockerfile
    restart: always
